version: "3"
services:
  springapp:
    image: lokeshhs591/spring-boot-mongo:1
    depends_on:
    - mongo
    ports:
    - 8080:8080
    networks:
    - springappbridge
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devops
    - MONGO_DB_PASSWORD=devops@123
  mongo:
    image: mongo
    volumes:
    - mongovol:/data/db
    environment:
    - MONGO_INITDB_USERNAME=devops
    - MONGO_INITDB_PASSWORD=devops@123
    networks:
    - springappbridge
volumes:
  mongovol:
networks:
  springappbridge:
